name: Go Build

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Build binary
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            go build -v -o ullm-${{ matrix.os }}-${{ matrix.arch }}.exe ./...
            echo "OUTPUT_NAME=ullm-${{ matrix.os }}-${{ matrix.arch }}.exe" >> $GITHUB_ENV
          else
            go build -v -o ullm-${{ matrix.os }}-${{ matrix.arch }} ./...
            echo "OUTPUT_NAME=ullm-${{ matrix.os }}-${{ matrix.arch }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Run tests
        run: go test -v ./...

      - name: Upload to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Uploading $OUTPUT_NAME to release"
          gh release upload "$GITHUB_REF_NAME" "$OUTPUT_NAME" --clobber