name: Go Build

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Build binary
        run: |
          OUTPUT_NAME=ullm-${{ matrix.os }}-${{ matrix.arch }}
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            OUTPUT_NAME="${OUTPUT_NAME}.exe"
          fi
          echo "OUTPUT_NAME=$OUTPUT_NAME" >> $GITHUB_ENV
          go build -v -o $OUTPUT_NAME ./...

      - name: Run tests
        run: go test -v ./...

      - uses: cli/gh-action@v2

      - name: Upload to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Uploading $OUTPUT_NAME to release"
          gh release upload "$GITHUB_REF_NAME" "$OUTPUT_NAME" --clobber