name: Go Build

on:
  release:
    types: [published]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
          
      - name: Build
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            go build -v -o ullm-${{ matrix.os }}-${{ matrix.arch }}.exe ./...
          else
            go build -v -o ullm-${{ matrix.os }}-${{ matrix.arch }} ./...
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: go test -v ./...

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.os == 'windows-latest' && format('./ullm-{0}-{1}.exe', matrix.os, matrix.arch) || format('./ullm-{0}-{1}', matrix.os, matrix.arch) }}
          asset_name: ${{ matrix.os == 'windows-latest' && format('ullm-{0}-{1}.exe', matrix.os, matrix.arch) || format('ullm-{0}-{1}', matrix.os, matrix.arch) }}
          asset_content_type: application/octet-stream